spring:
  application:
    name: ${APP_NAME:nwf}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/vn_listed_company}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:monokuro0207}
    hikari:
      poolName: ${spring.application.name}
      auto-commit: true
      register-mbeans: true
      idle-timeout: 600000
      minimum-idle: ${DB_CONN_MINIDLE:10}
      maximum-pool-size: ${DB_CONN_MAXACTIVE:100}
      connection-timeout: 30000
      max-lifetime: 1800000

server:
  port: 8081